add ObsOchestratorStorage for huaweiplugin.
openservicescloud/osc pull request #3
Opened 2023-01-05 06:59 UTC by Alice1319

add ObsOchestratorStorage for huaweiplugin.

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorageTest.java
> +//        storage.store("test");
Unused codes should be deleted.

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorageTest.java
> +        String value = "{\"name\":\"张三\",\"pwd\":123456}";
plz, avoid using Chinese.

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/test/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorageTest.java
> +        Assertions.assertEquals("{\"name\":\"张三\",\"pwd\":123456}",state);
plz, avoid using Chinese.

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
> +    public void closeObsClient(){
How about making it private?

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
> +            e.printStackTrace();
`log.info` is better.

2023-01-05 07:25 UTC, iskey commented on services/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
> +    public String getObjectKey(String sid, String pluginName, String key){
How about making it private?

2023-01-05 07:25 UTC, iskey commented on services/orchestrator/src/main/java/org/eclipse/osc/orchestrator/OrchestratorStorage.java
> +    void remove(String sid, String pluginName, String key);
Maybe not necessary, we can use `store("")` temporarily.

2023-01-05 07:25 UTC, iskey commented on services/orchestrator/src/main/java/org/eclipse/osc/orchestrator/OrchestratorStorage.java
> +    boolean exists(String sid, String pluginName, String key);
Maybe not necessary, we can use `getKey()` temporarily.

2023-01-05 10:36 UTC, Alice1319 commented
resolved  all the conversions.

2023-01-05 11:16 UTC, Alice1319 commented
resolved all the conversions and merge to huaweicloud osc.

2023-01-11 07:52 UTC, iskey requested changes

2023-01-11 07:52 UTC, iskey commented on plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
> +    private static final String ENDPOINT = "ENDPOINT";
```suggestion
    private static final String ENDPOINT = "HW_OBS_STORAGE_ENDPOINT";
```
For environment variables, we should make them more precise.

2023-01-11 07:52 UTC, iskey commented on plugins/huaweicloud/src/main/java/org/eclipse/osc/orchestrator/plugin/huaweicloud/ObsOrchestratorStorage.java
> +    private static final String LOCATION = "LOCATION";
```suggestion
    private static final String LOCATION = "HW_OBS_STORAGE_REGION";
```
How about we change it to `HW_OBS_STORAGE_REGION`.

2023-01-11 13:22 UTC, iskey commented
LGTM

2023-01-11 13:22 UTC, iskey approved these changes

2023-01-11 13:23 UTC, merged